image: node:12-alpine

cache:
  paths:
    - node_modules/

stages:
- build

build:
  stage: build
  only:
    - master
  artifacts:
    paths:
      - dist
  script:
  - yarn install --check-files --non-interactive
  - yarn run build
